# Generated by Django 3.2.14 on 2026-07-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoragentlistlog',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
