# Generated by Django 3.2.14 on 2025-09-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20250421_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoragentlist',
            options={},
        ),
    ]
