# Generated by Django 3.2.14 on 2025-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_doctoragentlist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoragentlist',
            name='modified_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctoragentlist',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
